version: '3.8'

services:
  glpi:
    build: .                                # Usa el Dockerfile
    container_name: glpi
    ports:
      - "8081:80"
    environment:
      - TZ=America/La_Paz
    volumes:
      - ./glpi/files:/var/www/html/files     # Persistencia
      - ./glpi/config:/var/www/html/config
      - ./plugins:/var/www/html/glpi/plugins      # Plugins externos opcionales
      - ./glpi-config/php/glpi.ini:/usr/local/etc/php/conf.d/glpi.ini
    depends_on:
      - glpi_db
    restart: unless-stopped

  glpi_db:
    image: mysql:8.0
    container_name: glpi_db
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: glpidb
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpipassword
    volumes:
      - glpi_db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  glpi_db_data:
